apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-operator-user-configuration
data:
  1-system-message.yaml: |
    jenkins:
      systemMessage: "Configuration as Code integration works!!!"
      sysdigSecure:
        debug: false
        enginemode: "anchoreengine"
        enginepass: "{vault:secret/data/accounts/sysdig#SDC_SECURE_TOKEN}"
        engineurl: "https://secures.sysdig.com/api/scanning/v1/anchore"
        engineverify: false
        useSudo: false