apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: scanning
spec:
  master:
    basePlugins:
      - name: kubernetes
        version: 1.25.2
      - name: workflow-job
        version: "2.39"
      - name: workflow-aggregator
        version: "2.6"
      - name: git
        version: 4.2.2
      - name: job-dsl
        version: "1.77"
      - name: configuration-as-code
        version: "1.38"
      - name: kubernetes-credentials-provider
        version: "0.13"
      - name: durable-task
        version: "1.33"
    plugins:
    - name: sysdig-secure
      version: "1.0.19.3"
    - name: prometheus
      version: 2.0.7
    - name: docker-workflow
      version: "1.23"
    - name: hashicorp-vault-plugin
      version: 3.6.0
    - name: simple-theme-plugin
      version: 0.5.1
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
  seedJobs:
  - id: spinnaker
    targets: "/jenkins/cicd/pipelines/*.jenkins"
    description: "Jenkins Operator repository"
    repositoryBranch: master
    repositoryUrl: https://github.com:0snug0/spinnaker.git
  configurationAsCode:
    configurations: 
    - name: jenkins-operator-user-configuration
    secret:
      name: sysdig-api-secret
  groovyScripts:
    configurations:
    - name: jenkins-operator-user-configuration